name: Build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  detekt:
    name: Run detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run detekt
        run: ./gradlew detekt

  build-release:
    name: Build release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build sample app
        run: ./gradlew :sample:assembleDebug
